# ###########################
# Playbook
# ###########################

- name: Webserver playbook
  hosts: localhost
  remote_user: edison
  become: true

  tasks:
    - name: Instalar Podman
      ansible.builtin.apt:
        name: podman
        state: present

    - name: Instalar Skopeo
      ansible.builtin.apt:
        name: skopeo
        state: present

    - name: Instalar Openssl
      ansible.builtin.apt:
        name: openssl
        state: present

    - name: Instalar Httpd-tools -> Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

